"""Controller for integrating Module 3 forecasts with Module 4 agents."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

from contracts import AgentRecommendation

# P1 - Production agents
from production_agents.cost_optimization_agent import CostOptimizationAgent
from production_agents.energy_allocator import EnergyAllocator
from production_agents.load_balancing_agent import LoadBalancingAgent
from production_agents.production_scheduler import ProductionScheduler

# P2 - Renewable agents
from renewable_agents.battery_management_agent import BatteryManagementAgent
from renewable_agents.grid_interaction_agent import GridInteractionAgent
from renewable_agents.renewable_agent import RenewableAgent
from renewable_agents.solar_dispatch_agent import SolarDispatchAgent

# P3 - Infrastructure agents
from infrastructure_agents.boiler_agent import BoilerAgent
from infrastructure_agents.compressor_agent import CompressorAgent
from infrastructure_agents.equipment_health_agent import EquipmentHealthAgent
from infrastructure_agents.hvac_agent import HVACAgent

from intelligence.decision_engine import DecisionEngine


class AgentController:
    """Connect Module 3 forecast output with all Module 4 agents."""

    name = "agent_controller"

    def __init__(
        self,
        *,
        decision_engine: DecisionEngine | None = None,
    ) -> None:
        self.decision_engine = decision_engine or DecisionEngine()

        # --------------------------------------------------------------
        # P1 - Production agents
        # --------------------------------------------------------------
        self.cost_agent = CostOptimizationAgent()
        self.load_balancing_agent = LoadBalancingAgent()
        self.production_scheduler = ProductionScheduler()
        self.energy_allocator = EnergyAllocator()

        # --------------------------------------------------------------
        # P2 - Renewable agents
        # --------------------------------------------------------------
        self.renewable_agent = RenewableAgent()
        self.solar_dispatch_agent = SolarDispatchAgent()
        self.battery_agent = BatteryManagementAgent()
        self.grid_agent = GridInteractionAgent()

        # --------------------------------------------------------------
        # P3 - Infrastructure agents
        # --------------------------------------------------------------
        self.hvac_agent = HVACAgent()
        self.compressor_agent = CompressorAgent()
        self.boiler_agent = BoilerAgent()
        self.health_agent = EquipmentHealthAgent()

        self._register_all_agents()

    # ==============================================================
    # MODULE 3 FORECAST LOADING
    # ==============================================================

    def load_forecast(
        self,
        forecast_path: str | Path,
    ) -> dict[str, Any]:
        """Load forecast_output.json generated by Module 3."""

        path = Path(forecast_path)

        if not path.exists():
            raise FileNotFoundError(
                f"Forecast file not found: {path}"
            )

        if path.suffix.lower() != ".json":
            raise ValueError(
                "forecast file must be a JSON file"
            )

        with path.open("r", encoding="utf-8") as file:
            data = json.load(file)

        if not isinstance(data, dict):
            raise ValueError(
                "forecast output must contain a JSON object"
            )

        return data

    # ==============================================================
    # MODULE 3 → MODULE 4 STATE MAPPING
    # ==============================================================

    def build_state(
        self,
        forecast: Mapping[str, Any],
    ) -> dict[str, Any]:
        """Convert Module 3 forecast output into Module 4 state."""

        future_state = forecast.get(
            "future_state",
            {},
        )

        energy_forecast = forecast.get(
            "energy_forecast",
            {},
        )

        if not isinstance(future_state, Mapping):
            raise ValueError(
                "future_state must be an object"
            )

        if not isinstance(energy_forecast, Mapping):
            raise ValueError(
                "energy_forecast must be an object"
            )

        # --------------------------------------------------------------
        # Values coming directly from Module 3
        # --------------------------------------------------------------

        units_per_hour = float(
            future_state.get(
                "units_per_hour",
                0,
            )
        )

        fuel_flow = float(
            future_state.get(
                "fuel_flow_m3_hr",
                energy_forecast.get(
                    "boiler_fuel_flow_m3_hr",
                    0,
                ),
            )
        )

        compressor_power = float(
            future_state.get(
                "compressor_power_kw",
                0,
            )
        )

        hvac_power = float(
            future_state.get(
                "hvac_power_kw",
                0,
            )
        )

        battery_power = float(
            future_state.get(
                "battery_power_kw",
                0,
            )
        )

        grid_import = float(
            energy_forecast.get(
                "grid_import_kw",
                future_state.get(
                    "grid_import_kw",
                    0,
                ),
            )
        )

        solar_power = float(
            future_state.get(
                "inverter_power_kw",
                0,
            )
        )

        renewable_generation = float(
            energy_forecast.get(
                "renewable_generation_kw",
                0,
            )
        )

        total_load = float(
            energy_forecast.get(
                "total_load_kw",
                0,
            )
        )

        # --------------------------------------------------------------
        # Derived values
        # --------------------------------------------------------------

        renewable_surplus = max(
            0.0,
            renewable_generation - total_load,
        )

        # --------------------------------------------------------------
        # Unified Module 4 state
        # --------------------------------------------------------------

        state: dict[str, Any] = {

            # ==========================================================
            # Module 3 forecast values
            # ==========================================================

            "units_per_hour": units_per_hour,

            "fuel_flow_m3_hr": fuel_flow,

            "compressor_power_kw": compressor_power,

            "hvac_power_kw": hvac_power,

            "battery_power_kw": battery_power,

            "grid_import_kw": grid_import,

            "inverter_power_kw": solar_power,

            "renewable_generation_kw": renewable_generation,

            "total_load_kw": total_load,

            # ==========================================================
            # P1 - Cost Optimization Agent
            # ==========================================================

            "production_load_kw": total_load,

            "production_demand_kw": total_load,

            "tariff_inr_kwh": 8.0,

            "off_peak_tariff_inr_kwh": 6.0,

            "grid_tariff_inr_kwh": 8.0,

            "flexible_load_fraction": 0.20,

            # ==========================================================
            # P1 - Load Balancing
            # ==========================================================

            "available_power_kw": total_load,

            # ==========================================================
            # P2 - Renewable Agent
            # ==========================================================

            "plant_demand_kw": total_load,

            "renewable_available_kw": renewable_generation,

            "solar_available_kw": solar_power,

            # ==========================================================
            # P2 - Solar Dispatch Agent
            # ==========================================================

            "solar_generation_kw": solar_power,

            "site_demand_kw": total_load,

            "battery_charge_headroom_kw": 40.0,

            "battery_charge_limit_kw": 50.0,

            "grid_export_limit_kw": 100.0,

            # ==========================================================
            # P2 - Battery Management
            # ==========================================================

            "state_of_charge_percent": 50.0,

            "capacity_kwh": 100.0,

            "battery_discharge_available_kw": abs(
                battery_power
            ),

            "battery_reserve_kw": 20.0,

            "maximum_charge_kw": 50.0,

            "maximum_discharge_kw": 50.0,

            "battery_cost_inr_kwh": 5.0,

            "interval_hours": 1.0,

            "renewable_surplus_kw": renewable_surplus,

            "site_deficit_kw": max(
                0.0,
                total_load - renewable_generation,
            ),

            # ==========================================================
            # P2 - Grid Interaction
            # ==========================================================

            "net_demand_kw": (
                total_load
                - renewable_generation
                - max(0.0, battery_power)
            ),

            "grid_import_limit_kw": max(
                500.0,
                grid_import,
            ),

            "export_price_inr_kwh": 4.0,

            # ==========================================================
            # P3 - HVAC
            # ==========================================================

            "temperature_c": 24.0,

            "target_temperature_c": 24.0,

            "minimum_temperature_c": 20.0,

            "maximum_temperature_c": 28.0,

            "maximum_hvac_power_kw": max(
                100.0,
                hvac_power,
            ),

            # ==========================================================
            # P3 - Compressor
            # ==========================================================

            "pressure_bar": 7.0,

            "target_pressure_bar": 6.0,

            "minimum_pressure_bar": 5.0,

            "maximum_compressor_power_kw": max(
                100.0,
                compressor_power,
            ),

            # ==========================================================
            # P3 - Boiler
            # ==========================================================

            "efficiency_percent": 85.0,

            "required_efficiency_percent": 70.0,

            "maximum_fuel_flow_m3_hr": max(
                200.0,
                fuel_flow,
            ),

            # ==========================================================
            # P3 - Equipment Health
            # ==========================================================

            "equipment": "plant_equipment",

            "health_score": 100.0,

            "anomaly_score": 0.0,

            "maintenance_due": False,

            # ==========================================================
            # Rule Engine
            # ==========================================================

            "unserved_load_kw": 0.0,
        }

        return state

    # ==============================================================
    # AGENT REGISTRATION
    # ==============================================================

    def _register_all_agents(self) -> None:
        """Register all P1, P2 and P3 agents."""

        # --------------------------------------------------------------
        # P1 - Production
        # --------------------------------------------------------------

        self.decision_engine.register_agent(
            "cost_optimization_agent",
            self._run_cost_optimization,
        )

        self.decision_engine.register_agent(
            "load_balancing_agent",
            self._run_load_balancing,
        )

        self.decision_engine.register_agent(
            "production_scheduler",
            self._run_production_scheduler,
        )

        self.decision_engine.register_agent(
            "energy_allocator",
            self._run_energy_allocator,
        )

        # --------------------------------------------------------------
        # P2 - Renewable
        # --------------------------------------------------------------

        self.decision_engine.register_agent(
            "renewable_agent",
            self._run_renewable,
        )

        self.decision_engine.register_agent(
            "solar_dispatch_agent",
            self._run_solar_dispatch,
        )

        self.decision_engine.register_agent(
            "battery_management_agent",
            self._run_battery,
        )

        self.decision_engine.register_agent(
            "grid_interaction_agent",
            self._run_grid,
        )

        # --------------------------------------------------------------
        # P3 - Infrastructure
        # --------------------------------------------------------------

        self.decision_engine.register_agent(
            "hvac_agent",
            self.hvac_agent.decide,
        )

        self.decision_engine.register_agent(
            "compressor_agent",
            self.compressor_agent.decide,
        )

        self.decision_engine.register_agent(
            "boiler_agent",
            self.boiler_agent.decide,
        )

        self.decision_engine.register_agent(
            "equipment_health_agent",
            self.health_agent.decide,
        )

    # ==============================================================
    # P1 ADAPTERS
    # ==============================================================

    def _run_cost_optimization(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P1 cost optimization agent."""

        return self.cost_agent.decide(
            state
        )

    def _run_load_balancing(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P1 load balancing agent."""

        available_power = max(
            0.0,
            float(
                state.get(
                    "available_power_kw",
                    state.get(
                        "total_load_kw",
                        0,
                    ),
                )
            ),
        )

        lines = {
            "production_line_A": {
                "requested_power_kw": available_power * 0.50,
                "minimum_power_kw": available_power * 0.20,
                "maximum_power_kw": available_power * 0.60,
                "priority_weight": 1.0,
            },
            "production_line_B": {
                "requested_power_kw": available_power * 0.50,
                "minimum_power_kw": available_power * 0.20,
                "maximum_power_kw": available_power * 0.60,
                "priority_weight": 1.0,
            },
        }

        return self.load_balancing_agent.decide(
            lines,
            available_power,
        )

    def _run_production_scheduler(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P1 production scheduler."""

        demand = max(
            0.0,
            float(
                state.get(
                    "total_load_kw",
                    0,
                )
            ),
        )

        jobs = [
            {
                "job_id": "forecast_production_job",
                "energy_kwh": demand,
                "deadline_slot": 0,
                "priority_weight": 1.0,
            }
        ]

        slots = [
            {
                "slot_id": "current_forecast_slot",
                "capacity_kwh": demand,
                "renewable_kwh": max(
                    0.0,
                    float(
                        state.get(
                            "renewable_generation_kw",
                            0,
                        )
                    ),
                ),
                "tariff_inr_kwh": float(
                    state.get(
                        "tariff_inr_kwh",
                        8.0,
                    )
                ),
            }
        ]

        return self.production_scheduler.decide(
            jobs,
            slots,
        )

    def _run_energy_allocator(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P1 energy allocator."""

        return self.energy_allocator.decide(
            state
        )

    # ==============================================================
    # P2 ADAPTERS
    # ==============================================================

    def _run_renewable(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P2 renewable agent."""

        return self.renewable_agent.decide(
            state
        )

    def _run_solar_dispatch(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P2 solar dispatch agent."""

        return self.solar_dispatch_agent.decide(
            state
        )

    def _run_battery(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P2 battery management agent."""

        return self.battery_agent.decide(
            state
        )

    def _run_grid(
        self,
        state: Mapping[str, Any],
    ) -> AgentRecommendation:
        """Run P2 grid interaction agent."""

        grid_state = dict(state)

        total_load = float(
            state.get(
                "total_load_kw",
                0,
            )
        )

        renewable = float(
            state.get(
                "renewable_generation_kw",
                0,
            )
        )

        battery_power = float(
            state.get(
                "battery_power_kw",
                0,
            )
        )

        grid_state["net_demand_kw"] = (
            total_load
            - renewable
            - max(
                0.0,
                battery_power,
            )
        )

        return self.grid_agent.decide(
            grid_state
        )

    # ==============================================================
    # COMPLETE PIPELINE
    # ==============================================================

    def generate_recommendations(
        self,
        forecast: Mapping[str, Any],
        *,
        include_rules: bool = True,
    ) -> list[AgentRecommendation]:
        """Run all registered agents on a Module 3 forecast."""

        state = self.build_state(
            forecast
        )

        return self.decision_engine.decide(
            state,
            include_rules=include_rules,
        )

    def process_file(
        self,
        forecast_path: str | Path,
        *,
        include_rules: bool = True,
    ) -> list[AgentRecommendation]:
        """Load Module 3 forecast and run complete Module 4 pipeline."""

        forecast = self.load_forecast(
            forecast_path
        )

        return self.generate_recommendations(
            forecast,
            include_rules=include_rules,
        )

    def summarize(
        self,
        recommendations: list[AgentRecommendation],
    ) -> dict[str, Any]:
        """Summarize generated recommendations."""

        return self.decision_engine.summarize(
            recommendations
        )

    def registered_agents(self) -> list[str]:
        """Return all registered agents."""

        return self.decision_engine.get_registered_agents()